### PR TITLE
lolow updates merged

### PR DESCRIPTION
**Pull request by JohannesEmm**

### CODE REVIEW

**Comment by lolow** [comment]
I did not check if these changes are impacting the other tabs and the other plot script, but thanks for the merge.

**Comment by JohannesEmm** [comment]
Hi,

yes I tried, but not sure I can merge it, tried both ways but I am afraid to mess some things up. 
So not merging for now, but if you think its managgeable feel free to do so. the gdxcompar improvements would be good to have across the three different versions.

but we can also discuss.
thanks!
On 29/11/2023 12:25:29, Laurent Drouet ***@***.***> wrote:
I did not check if these changes are impacting the other tabs and the other plot script, but thanks for the merge.

**Comment by lolow** [comment]
I have placed the pull request in draft mode to review the file changes that are eligible for merging into the master branch.

**Comment by JohannesEmm** [comment]
sure. the sliders I now merged, if there are other improvements decide if you wnt to create a separate branch or keep this. thanks a lot!

**Pull request closed without merging**
